---
galaxy_info:
  role_name: service_armadillo
  author: Sido Haakma
  description: Armadillo service that handles requests from the DataSHIELD client and secures the data to be non-disclosive
  company: MOLGENIS

  license: LGPL

  min_ansible_version: "2.9"

  platforms:
    - name: EL
      versions:
        - "8"
        - "7"
    - name: Ubuntu
      versions:
        - focal
    - name: Debian
      versions:
        - buster

  galaxy_tags: [federation]

dependencies: []
