---
galaxy_info:
  role_name: service_auth
  author: Sido Haakma
  description: Armadillo authentication implementation used allow people to use the Armadillo suite
  company: MOLGENIS

  license: LGPL

  min_ansible_version: "2.9"

  platforms:
    - name: EL
      versions:
        - "8"
        - "7"
    - name: Ubuntu
      versions:
        - focal
    - name: Debian
      versions:
        - buster

  galaxy_tags: [federation]

allow_duplicates: true
