---
galaxy_info:
  role_name: docker
  author: Sido Haakma
  description: Docker used to run containers on the OS
  company: MOLGENIS

  license: LGPL

  min_ansible_version: 1.2

  github_branch: master

  platforms:
    - name: Ubuntu
      versions:
        - 20
    - name: Debian
      versions:
        - 10

  galaxy_tags: [federation]

dependencies: []
