---
galaxy_info:
  role_name: post_nginx
  author: Sido Haakma
  description: A webserver to proxy the different services on the Armadillo deployment
  company: MOLGENIS

  license: LGPL

  min_ansible_version: "2.9"

  platforms:
    - name: EL
      versions:
        - "8"
        - "7"
    - name: Ubuntu
      versions:
        - focal
    - name: Debian
      versions:
        - buster

  galaxy_tags: [federation]

dependencies: []
