---
galaxy_info:
  role_name: rserver
  author: Sido Haakma
  description: RServer implementation used to perform local analysis and send aggregated results to the Aramdillo
  company: MOLGENIS

  license: LGPL

  min_ansible_version: 1.2

  github_branch: master

  platforms:
    - name: Ubuntu
      versions:
        - 20
    - name: Debian
      versions:
        - 10
    - name: CentOS
      versions:
        - 8
        - 7
    - name: RedHat
      versions:
        - 8
        - 7

  galaxy_tags: [federation]

allow_duplicates: true
