---
galaxy_info:
  role_name: service_minio
  author: Sido Haakma
  description: Minio file storage, used to get data into the federated platform
  company: MOLGENIS

  license: LGPL

  min_ansible_version: "2.9"

  platforms:
    - name: EL
      versions:
        - "8"
        - "7"
    - name: Ubuntu
      versions:
        - focal
    - name: Debian
      versions:
        - buster

  galaxy_tags: [federation, molgenis]

dependencies: []
